Repository opendilab/LightZero, pull requests merged in 2023-12, with the labels that each got.

#161 polish(xcy): polish the comments and render methods in BipedalWalker, Bsuite, MuJoCo, and MiniGrid
  requirements.txt
  zoo/box2d/bipedalwalker/entry/bipedalwalker_eval.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_cont_disc_env.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_env.py
  zoo/bsuite/config/bsuite_muzero_config.py
  zoo/bsuite/entry/bsuite_eval_config.py
  zoo/bsuite/envs/bsuite_lightzero_env.py
  zoo/minigrid/entry/minigrid_eval.py
  zoo/minigrid/envs/minigrid_lightzero_env.py
  zoo/mujoco/envs/mujoco_disc_lightzero_env.py
  zoo/mujoco/envs/mujoco_lightzero_env.py
Labels: documentation, style, config

#160 polish(pu): polish action_type and env_type, fix test.yml, fix unittest
  .github/workflows/test.yml
  lzero/envs/tests/test_ding_env_wrapper.py
  lzero/mcts/buffer/game_buffer.py
  lzero/mcts/buffer/game_buffer_efficientzero.py
  lzero/mcts/buffer/game_buffer_gumbel_muzero.py
  lzero/mcts/buffer/game_buffer_muzero.py
  lzero/mcts/buffer/game_buffer_sampled_efficientzero.py
  lzero/mcts/buffer/game_buffer_stochastic_muzero.py
  lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp
  lzero/mcts/ptree/ptree_az.py
  lzero/mcts/tests/config/tictactoe_muzero_bot_mode_config_for_test.py
  lzero/mcts/tests/test_game_buffer.py
  lzero/policy/efficientzero.py
  lzero/policy/gumbel_muzero.py
  lzero/policy/muzero.py
  lzero/policy/sampled_efficientzero.py
  lzero/policy/stochastic_muzero.py
  requirements.txt
  zoo/board_games/connect4/config/connect4_alphazero_bot_mode_config.py
  zoo/board_games/connect4/config/connect4_alphazero_sp_mode_config.py
  zoo/board_games/connect4/config/connect4_muzero_bot_mode_config.py
  zoo/board_games/connect4/config/connect4_muzero_sp_mode_config.py
  zoo/board_games/gomoku/config/gomoku_alphazero_bot_mode_config.py
  zoo/board_games/gomoku/config/gomoku_alphazero_sp_mode_config.py
  zoo/board_games/gomoku/config/gomoku_gumbel_muzero_bot_mode_config.py
  zoo/board_games/gomoku/config/gomoku_muzero_bot_mode_config.py
  zoo/board_games/gomoku/config/gomoku_muzero_sp_mode_config.py
  zoo/board_games/gomoku/config/gomoku_sampled_alphazero_bot_mode_config.py
  zoo/board_games/gomoku/config/gomoku_sampled_alphazero_sp_mode_config.py
  zoo/board_games/gomoku/envs/gomoku_env.py
  zoo/board_games/gomoku/test/test_gomoku_env_legal_actions.py
  zoo/board_games/tictactoe/config/tictactoe_alphazero_bot_mode_config.py
  zoo/board_games/tictactoe/config/tictactoe_gumbel_muzero_bot_mode_config.py
  zoo/board_games/tictactoe/config/tictactoe_muzero_bot_mode_config.py
  zoo/board_games/tictactoe/config/tictactoe_muzero_sp_mode_config.py
  zoo/box2d/lunarlander/config/lunarlander_cont_disc_efficientzero_config.py
  zoo/box2d/lunarlander/config/lunarlander_cont_disc_sampled_efficientzero_config.py
  zoo/box2d/lunarlander/config/lunarlander_disc_gumbel_muzero_config.py
  zoo/box2d/lunarlander/envs/lunarlander_cont_disc_env.py
  zoo/box2d/lunarlander/envs/lunarlander_env.py
  zoo/classic_control/cartpole/config/cartpole_muzero_config.py
  zoo/classic_control/pendulum/config/pendulum_cont_disc_gumbel_muzero_config.py
  zoo/classic_control/pendulum/config/pendulum_cont_disc_muzero_config.py
Labels: bug, enhancement, dependencies, config

#168 fix(pu): fix action_mask in bipedalwalker_cont_disc_env, fix device bug in sampled efficientzero
  lzero/policy/sampled_efficientzero.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_cont_disc_env.py
  zoo/box2d/lunarlander/envs/lunarlander_cont_disc_env.py
Labels: bug

#173 fix(xcy): fix render settings when using gymnasium
  requirements.txt
  zoo/atari/entry/atari_eval.py
  zoo/atari/envs/atari_wrappers.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_cont_disc_env.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_env.py
  zoo/box2d/lunarlander/envs/lunarlander_cont_disc_env.py
  zoo/box2d/lunarlander/envs/lunarlander_env.py
  zoo/classic_control/cartpole/envs/cartpole_lightzero_env.py
  zoo/classic_control/pendulum/entry/pendulum_eval.py
  zoo/classic_control/pendulum/envs/pendulum_lightzero_env.py
  zoo/minigrid/envs/minigrid_lightzero_env.py
Labels: bug, config

#177 polish(pu): polish redundent data squeeze operations
  lzero/policy/sampled_efficientzero.py
  zoo/box2d/lunarlander/config/lunarlander_cont_sampled_efficientzero_config.py
Labels: efficiency optimization

#178 fix(lxy): fix completed value inf bug when zero exists in action_mask in gumbel muzero
  lzero/policy/gumbel_muzero.py
Labels: bug
