Repository opendilab/LightZero, pull requests merged in 2023-08, with the labels that each got.

#54 feature(yzj): add eps greedy option and add random collect in train_muzero_entry on ez/mz
  lzero/entry/train_muzero.py
  lzero/entry/utils.py
  lzero/policy/efficientzero.py
  lzero/policy/muzero.py
  lzero/policy/random_policy.py
  lzero/worker/muzero_collector.py
  zoo/atari/config/atari_efficientzero_config.py
  zoo/atari/config/atari_muzero_config.py
Labels: enhancement

#57 doc(xcy): polish mcts bot comments
  lzero/mcts/ptree/ptree_az.py
  zoo/atari/config/atari_muzero_config.py
  zoo/board_games/mcts_bot.py
  zoo/board_games/test_speed_win-rate_between_bots.py
  zoo/board_games/tictactoe/config/tictactoe_muzero_bot_mode_config.py
Labels: documentation, polish

#61 doc(xcy): polish comments in alphazero ptree_az.py
  lzero/mcts/ptree/ptree_az.py
Labels: documentation, enhancement

#70 fix(yzj): fix random and eps greedy explore on sez
  lzero/policy/sampled_efficientzero.py
Labels: bug

#68 feature(pu): add ez/mz/az pytorch ddp support
  lzero/config/utils.py
  lzero/entry/train_muzero.py
  lzero/policy/alphazero.py
  lzero/policy/efficientzero.py
  lzero/policy/gumbel_muzero.py
  lzero/policy/muzero.py
  lzero/policy/sampled_efficientzero.py
  lzero/worker/alphazero_collector.py
  lzero/worker/alphazero_evaluator.py
  lzero/worker/muzero_collector.py
  lzero/worker/muzero_evaluator.py
  zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py
  zoo/atari/config/atari_muzero_multigpu_ddp_config.py
  zoo/board_games/tictactoe/config/tictactoe_alphazero_bot_mode_multigpu_ddp_config.py
  zoo/board_games/tictactoe/config/tictactoe_alphazero_sp_mode_multigpu_ddp_config.py
Labels: enhancement

#74 fix(yzj): fix priority bug in muzero collector
  lzero/policy/efficientzero.py
  lzero/policy/gumbel_muzero.py
  lzero/policy/muzero.py
  lzero/policy/sampled_efficientzero.py
  lzero/worker/muzero_collector.py
Labels: bug

#78 doc(pu): add init version of doc about how to customize envs and algos
  docs/source/tutorials/algos/customize_algos.md
  docs/source/tutorials/algos/customize_algos_zh.md
  docs/source/tutorials/envs/customize_envs.md
  docs/source/tutorials/envs/customize_envs_zh.md
Labels: documentation

#77 feature(pu): add 2048 and minigrid benchmark
  README.md
  README.zh.md
  assets/benchmark/main/2048/2048_stochasticmz_mz.png
  assets/benchmark/main/2048/2048_stochasticmz_mz_nc5.png
  assets/benchmark/main/minigrid/fourrooms_exploration.png
  assets/benchmark/main/minigrid/keycorridors3r3.png
  assets/benchmark/main/minigrid/keycorridors3r3_exploration.png
Labels: documentation
