Repository opendilab/LightZero, pull requests merged in 2023-09, with the labels that each got.

#75 config(lxy): modify sez bipedalwalker config
  zoo/box2d/bipedalwalker/config/bipedalwalker_cont_disc_efficientzero_config.py
  zoo/box2d/bipedalwalker/config/bipedalwalker_cont_disc_sampled_efficientzero_config.py
  zoo/box2d/bipedalwalker/config/bipedalwalker_cont_sampled_efficientzero_config.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_cont_disc_env.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_env.py
Labels: config

#89 doc(hus): update AlphaZero paper_note
  assets/paper_notes/AlphaZero.pdf
Labels: documentation

#96 polish(pu): update the supported env and algo list
  README.md
  README.zh.md
  zoo/README.md
Labels: documentation

#95 feature(pu): add Dockerfile and its usage instructions
  Dockerfile
  README.md
  README.zh.md
Labels: documentation, enhancement
