Repository opendilab/LightZero, pull requests merged in 2023-10, with the labels that each got.

#104 fix(elto): typo in README.md
  README.md
Labels: documentation

#109 fix(soham): fix typo in README.md
  README.md
Labels: documentation

#107 feature(xcy): add muzero config for connect4
  zoo/board_games/connect4/config/connect4_muzero_bot_mode_config.py
  zoo/board_games/connect4/config/connect4_muzero_sp_mode_config.py
Labels: config

#106 polish(xcy): update env and algo tutorial doc
  docs/source/tutorials/algos/customize_algos.md
  docs/source/tutorials/algos/customize_algos_zh.md
  docs/source/tutorials/envs/customize_envs.md
  docs/source/tutorials/envs/customize_envs_zh.md
Labels: documentation

#111 polish(prajjwalyd): added a back to top button in readme.md
  README.md
Labels: documentation, good first issue

#113 polish(suravshresth): fix typos in ptree_mz.py
  lzero/mcts/ptree/ptree_mz.py
Labels: documentation

#116 polish(prajjwalyd): add a back to top button in README.zh.md
  README.zh.md
Labels: documentation

#119 feature(armaan): added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, good first issue

#120 fix(pu): fix mcts and alphabeta bot unittest, polish simulation method of ptree_az
  README.md
  README.zh.md
  lzero/mcts/ctree/ctree_sampled_efficientzero/lib/cnode.cpp
  lzero/mcts/ptree/ptree_az.py
  lzero/policy/alphazero.py
  lzero/worker/alphazero_collector.py
  lzero/worker/alphazero_evaluator.py
  zoo/board_games/alphabeta_pruning_bot.py
  zoo/board_games/gomoku/config/gomoku_alphazero_bot_mode_config.py
  zoo/board_games/gomoku/config/gomoku_alphazero_sp_mode_config.py
  zoo/board_games/mcts_bot.py
  zoo/board_games/test_speed_win-rate_between_bots.py
  zoo/board_games/tictactoe/config/tictactoe_alphazero_bot_mode_config.py
  zoo/board_games/tictactoe/config/tictactoe_alphazero_bot_mode_multigpu_ddp_config.py
  zoo/board_games/tictactoe/config/tictactoe_alphazero_sp_mode_config.py
  zoo/board_games/tictactoe/config/tictactoe_alphazero_sp_mode_multigpu_ddp_config.py
  zoo/board_games/tictactoe/envs/tictactoe_env.py
Labels: bug, enhancement

#118 feature(pu): add random_policy support for continuous env
  lzero/entry/utils.py
  lzero/mcts/tests/cprofile_mcts_ptree.py
  lzero/mcts/tests/eval_tree_speed.py
  lzero/mcts/tests/test_mcts_ctree.py
  lzero/policy/efficientzero.py
  lzero/policy/gumbel_muzero.py
  lzero/policy/muzero.py
  lzero/policy/random_policy.py
  lzero/policy/sampled_efficientzero.py
  lzero/policy/stochastic_muzero.py
  lzero/worker/muzero_collector.py
  zoo/box2d/lunarlander/config/lunarlander_cont_sampled_efficientzero_config.py
Labels: enhancement, discussion

#123 feature(priyanshu): added .gitpod.yml and .gitpod.Dockerfile
  .gitpod.Dockerfile
  .gitpod.yml
Labels: enhancement, config

#127 feature(dhote): added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, good first issue
