Repository opendilab/LightZero, pull requests merged in 2024-03, with the labels that each got.

#188 feature(pu): add eval_offline option
  lzero/entry/train_muzero.py
  lzero/policy/efficientzero.py
  lzero/policy/gumbel_muzero.py
  lzero/policy/muzero.py
  lzero/policy/sampled_efficientzero.py
  lzero/policy/stochastic_muzero.py
Labels: enhancement

#186 test(pu): add unittest for game_buffer_muzero
  lzero/mcts/buffer/game_segment.py
  lzero/mcts/tests/test_game_segment.py
  lzero/mcts/tests/test_muzero_game_buffer.py
  lzero/policy/tests/config/atari_muzero_config_for_test.py
Labels: enhancement, style

#194 polish(pu): add load pretrained model option in test_game_segment
  lzero/mcts/tests/config/tictactoe_muzero_bot_mode_config_for_test.py
  lzero/mcts/tests/test_game_segment.py
Labels: polish

#191 polish(pu): polish _forward_learn() and some data process operations
  lzero/mcts/buffer/game_buffer.py
  lzero/mcts/buffer/game_buffer_muzero.py
  lzero/mcts/buffer/game_segment.py
  lzero/mcts/tests/config/atari_efficientzero_config_for_test.py
  lzero/mcts/tests/test_mcts_ctree.py
  lzero/mcts/tests/test_mcts_ptree.py
  lzero/mcts/tests/test_mcts_sampled_ctree.py
  lzero/mcts/tests/test_muzero_game_buffer.py
  lzero/mcts/tree_search/mcts_ctree.py
  lzero/mcts/tree_search/mcts_ctree_sampled.py
  lzero/mcts/tree_search/mcts_ctree_stochastic.py
  lzero/mcts/tree_search/mcts_ptree.py
  lzero/mcts/tree_search/mcts_ptree_sampled.py
  lzero/mcts/tree_search/mcts_ptree_stochastic.py
  lzero/mcts/utils.py
  lzero/policy/efficientzero.py
  lzero/policy/gumbel_muzero.py
  lzero/policy/muzero.py
  lzero/policy/sampled_alphazero.py
  lzero/policy/sampled_efficientzero.py
  lzero/policy/stochastic_muzero.py
  lzero/policy/utils.py
  lzero/worker/muzero_collector.py
  zoo/atari/config/atari_muzero_config.py
  zoo/atari/envs/atari_lightzero_env.py
  zoo/board_games/tictactoe/envs/test_tictactoe_env.py
  zoo/board_games/tictactoe/envs/tictactoe_env.py
Labels: efficiency optimization

#190 feature(xcy): save the updated searched results to the buffer during reanalyze
  lzero/mcts/buffer/game_buffer_efficientzero.py
  lzero/mcts/buffer/game_buffer_muzero.py
  lzero/mcts/buffer/game_buffer_sampled_efficientzero.py
  lzero/mcts/ctree/ctree_efficientzero/lib/cnode.cpp
  lzero/mcts/ctree/ctree_muzero/lib/cnode.cpp
  lzero/mcts/ptree/ptree_ez.py
  lzero/policy/efficientzero.py
  lzero/policy/gumbel_muzero.py
  lzero/policy/muzero.py
  lzero/policy/sampled_efficientzero.py
  lzero/policy/stochastic_muzero.py
  zoo/atari/config/atari_muzero_config.py
Labels: enhancement

#200 fix(pu): fix sync_gradients and log in DDP settings
  lzero/entry/train_muzero.py
  lzero/entry/utils.py
  lzero/mcts/tests/test_muzero_game_buffer.py
  lzero/model/common.py
  lzero/model/efficientzero_model.py
  lzero/policy/efficientzero.py
  lzero/policy/muzero.py
  zoo/atari/config/atari_efficientzero_multigpu_ddp_config.py
  zoo/atari/config/atari_muzero_multigpu_ddp_config.py
Labels: bug, enhancement, config

#181 feature(rjy): add mtcar env and muzero visualization
  lzero/worker/muzero_evaluator.py
  zoo/classic_control/mountain_car/__init__.py
  zoo/classic_control/mountain_car/config/mtcar_muzero_config.py
  zoo/classic_control/mountain_car/entry/__init__.py
  zoo/classic_control/mountain_car/entry/mountain_car_eval.py
  zoo/classic_control/mountain_car/entry/visualize_mz_mtcar.ipynb
  zoo/classic_control/mountain_car/envs/__init__.py
  zoo/classic_control/mountain_car/envs/mtcar_lightzero_env.py
  zoo/classic_control/mountain_car/envs/test_mtcar_env.py
Labels: enhancement, environment

#197 feature(pu): add MemoryEnv and related configs
  lzero/mcts/tests/test_game_segment.py
  requirements.txt
  zoo/README.md
  zoo/atari/envs/atari_lightzero_env.py
  zoo/atari/tests/test_atari_lightzero_env.py
  zoo/atari/tests/test_atari_lightzero_env_visualization.py
  zoo/memory/__init__.py
  zoo/memory/config/__init__.py
  zoo/memory/config/memory_efficientzero_config.py
  zoo/memory/config/memory_muzero_config.py
  zoo/memory/config/memory_muzero_rnd_config.py
  zoo/memory/config/memory_sampled_efficientzero_config.py
  zoo/memory/entry/__init__.py
  zoo/memory/entry/memory_eval.py
  zoo/memory/envs/__init__.py
  zoo/memory/envs/memory_lightzero_env.py
  zoo/memory/envs/pycolab_tvt/__init__.py
  zoo/memory/envs/pycolab_tvt/common.py
  zoo/memory/envs/pycolab_tvt/game.py
  zoo/memory/envs/pycolab_tvt/human_player.py
  zoo/memory/envs/pycolab_tvt/key_to_door.py
  zoo/memory/envs/pycolab_tvt/objects.py
  zoo/memory/envs/pycolab_tvt/readme.md
  zoo/memory/envs/pycolab_tvt/visual_match.py
  zoo/memory/envs/test_memory_lightzero_env.py
  zoo/memory/envs/test_render.py
  zoo/memory/key_to_door.gif
  zoo/memory/visual_match.gif
  zoo/mujoco/envs/mujoco_lightzero_env.py
Labels: environment, config
