Repository opendilab/LightZero, pull requests merged in 2024-11, with the labels that each got.

#290 fix(roland): fix typo in model/utils.py
  lzero/model/utils.py
Labels: typo

#295 feature(pu): add atari100k metric utils
  zoo/atari/compute_normalized_mean_and_median_atari100k.py
  zoo/atari/read_atari_results_from_txt.py
Labels: config

#296 feature(pu): add eval_benchmark test
  zoo/box2d/bipedalwalker/envs/bipedalwalker_cont_disc_env.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_env.py
  zoo/box2d/lunarlander/envs/lunarlander_cont_disc_env.py
  zoo/box2d/lunarlander/envs/lunarlander_env.py
  zoo/bsuite/envs/bsuite_lightzero_env.py
  zoo/classic_control/cartpole/config/cartpole_unizero_config.py
  zoo/classic_control/mountain_car/config/mountain_car_muzero_config.py
  zoo/classic_control/mountain_car/entry/mountain_car_eval.py
  zoo/classic_control/mountain_car/envs/mtcar_lightzero_env.py
  zoo/classic_control/pendulum/envs/pendulum_lightzero_env.py
  zoo/dmc2gym/envs/dmc2gym_lightzero_env.py
  zoo/eval_benchmark.py
  zoo/minigrid/envs/minigrid_lightzero_env.py
  zoo/mujoco/envs/mujoco_disc_lightzero_env.py
  zoo/mujoco/envs/mujoco_lightzero_env.py
Labels: enhancement

#297 fix(pu): fix smz compile_args and num_simulations bug in world_model
  lzero/config/meta.py
  lzero/entry/__init__.py
  lzero/mcts/ctree/ctree_sampled_muzero/lib/cnode.cpp
  lzero/mcts/ctree/ctree_sampled_muzero/lib/cnode.h
  lzero/model/__init__.py
  lzero/model/unizero_model.py
  lzero/model/unizero_world_models/tokenizer.py
  lzero/model/unizero_world_models/world_model.py
  lzero/policy/utils.py
  lzero/reward_model/__init__.py
  requirements.txt
  setup.py
Labels: bug

#298 polish(pu): polish requirements
  README.md
  README.zh.md
  requirements.txt
  zoo/bsuite/envs/bsuite_lightzero_env.py
  zoo/bsuite/envs/check_bsuite_config.py
  zoo/memory/envs/pycolab_tvt/common.py
  zoo/memory/envs/pycolab_tvt/human_player.py
  zoo/memory/envs/pycolab_tvt/key_to_door.py
  zoo/memory/envs/pycolab_tvt/objects.py
  zoo/memory/envs/pycolab_tvt/visual_match.py
  zoo/pooltool/sum_to_three/envs/sum_to_three_env.py
  zoo/pooltool/sum_to_three/envs/test_sum_to_three_env.py
Labels: polish
