Repository opendilab/LightZero, pull requests merged in 2024-08, with the labels that each got.

#192 feature(xcy): add Metadrive Env and configs
  requirements-build.txt
  requirements-doc.txt
  requirements-test.txt
  requirements.txt
  zoo/metadrive/config/metadrive_sampled_efficientzero_config.py
  zoo/metadrive/env/drive_env.py
  zoo/metadrive/env/metadrive_env.py
Labels: environment, algorithm

#259 feature(hus): add self-hosted linux(ubuntu) ci runner
  .github/workflows/test.yml
  requirements.txt
Labels: style

#254 fix(pu): fix DownSample for different obs shape
  lzero/model/common.py
Labels: bug, enhancement
