Repository opendilab/LightZero, pull requests merged in 2024-09, with the labels that each got.

#272 feature(pu): polish chess env and its render method, add unittest and configs
  lzero/entry/train_alphazero.py
  lzero/policy/alphazero.py
  zoo/board_games/chess/config/chess_alphazero_bot_mode_config.py
  zoo/board_games/chess/config/chess_alphazero_sp-mode_config.py
  zoo/board_games/chess/config/chess_alphazero_sp_mode_config.py
  zoo/board_games/chess/envs/chess_env.py
  zoo/board_games/chess/envs/chess_lightzero_env.py
  zoo/board_games/chess/envs/eval_chess_env_human.py
  zoo/board_games/chess/envs/img/bishop_black.png
  zoo/board_games/chess/envs/img/bishop_white.png
  zoo/board_games/chess/envs/img/chessboard.png
  zoo/board_games/chess/envs/img/king_black.png
  zoo/board_games/chess/envs/img/king_white.png
  zoo/board_games/chess/envs/img/knight_black.png
  zoo/board_games/chess/envs/img/knight_white.png
  zoo/board_games/chess/envs/img/pawn_black.png
  zoo/board_games/chess/envs/img/pawn_white.png
  zoo/board_games/chess/envs/img/queen_black.png
  zoo/board_games/chess/envs/img/queen_white.png
  zoo/board_games/chess/envs/img/rook_black.png
  zoo/board_games/chess/envs/img/rook_white.png
  zoo/board_games/chess/envs/test_chess_env.py
  zoo/board_games/chess/envs/test_chess_env_auto.py
  zoo/board_games/chess/envs/test_chess_env_human.py
  zoo/board_games/chess/envs/test_chess_lightzero_env.py
Labels: enhancement, environment, config

#275 fix(sk): fix wrong chance values in stochastic muzero
  lzero/mcts/buffer/game_buffer_stochastic_muzero.py
Labels: bug

#245 feature(pu): adopt alphazero to non-zero-sum games
  lzero/mcts/ptree/ptree_az.py
  lzero/policy/alphazero.py
  zoo/board_games/tictactoe/config/dummy_any_game_alphazero_self_play_mode_config.py
  zoo/board_games/tictactoe/config/dummy_any_game_alphazero_single_player_mode_config.py
  zoo/board_games/tictactoe/envs/dummy_any_game_env.py
  zoo/board_games/tictactoe/envs/tictactoe_env.py
Labels: enhancement, environment
