Repository opendilab/LightZero, pull requests merged in 2025-04, with the labels that each got.

#339 fix(pu): fix timestep compatibility
  lzero/mcts/buffer/game_segment.py
  lzero/mcts/ptree/ptree_ez.py
  lzero/mcts/ptree/ptree_mz.py
  lzero/mcts/ptree/ptree_sez.py
  lzero/mcts/ptree/ptree_stochastic_mz.py
  lzero/policy/efficientzero.py
  lzero/policy/gumbel_muzero.py
  lzero/policy/muzero.py
  lzero/policy/muzero_rnn_full_obs.py
  lzero/policy/sampled_efficientzero.py
  lzero/policy/sampled_muzero.py
  lzero/policy/sampled_unizero.py
  lzero/policy/stochastic_muzero.py
  lzero/policy/unizero.py
  lzero/worker/muzero_collector.py
  lzero/worker/muzero_evaluator.py
  lzero/worker/muzero_segment_collector.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_cont_disc_env.py
  zoo/box2d/bipedalwalker/envs/bipedalwalker_env.py
  zoo/box2d/lunarlander/envs/lunarlander_cont_disc_env.py
  zoo/box2d/lunarlander/envs/lunarlander_env.py
  zoo/classic_control/cartpole/envs/cartpole_lightzero_env.py
  zoo/classic_control/mountain_car/envs/mtcar_lightzero_env.py
  zoo/classic_control/pendulum/envs/pendulum_lightzero_env.py
  zoo/jericho/envs/jericho_env.py
  zoo/minigrid/envs/minigrid_lightzero_env.py
Labels: bug

#342 fix(pu): fix reanalyze_ratio compatibility with rope embed
  lzero/mcts/buffer/game_buffer_unizero.py
  zoo/classic_control/cartpole/config/cartpole_unizero_config.py
Labels: bug

#347 fix(lkj): fix typo in customize_envs.md
  docs/source/tutorials/envs/customize_envs.md
Labels: documentation, typo

#345 fix(pu): fix atari and dmc2gym env to support shared_memory
  .gitignore
  zoo/atari/config/atari_muzero_config.py
  zoo/atari/envs/atari_lightzero_env.py
  zoo/dmc2gym/envs/dmc2gym_lightzero_env.py
Labels: enhancement

#348 feature(xjy): add decode text regularization option and related logs
  lzero/mcts/tree_search/mcts_ctree.py
  lzero/model/unizero_model.py
  lzero/model/unizero_world_models/tokenizer.py
  lzero/model/unizero_world_models/world_model.py
  lzero/policy/unizero.py
  lzero/policy/utils.py
  lzero/worker/muzero_collector.py
  lzero/worker/muzero_evaluator.py
  zoo/jericho/configs/jericho_unizero_ddp_config.py
Labels: enhancement
