Repository opendilab/LightZero, pull requests merged in 2025-03, with the labels that each got.

#327 fix(pu): fix obs_shape tuple bug in initialize_zeros_batch
  lzero/entry/utils.py
Labels: bug

#328 fix(pu): fix prepare_obs_stack_for_unizero
  lzero/policy/sampled_unizero.py
  lzero/policy/unizero.py
  lzero/policy/utils.py
Labels: bug

#330 polish(xjy): update configuration and log instructions in tutorials
  docs/source/tutorials/config/config.md
  docs/source/tutorials/config/config_zh.md
  docs/source/tutorials/logs/logs.md
  docs/source/tutorials/logs/logs_zh.md
Labels: documentation

#307 feature(whl/pu): add jericho environments and related configs
  docs/source/_templates/layout.html
  lzero/entry/train_unizero.py
  lzero/entry/train_unizero_segment.py
  lzero/entry/utils.py
  lzero/mcts/buffer/game_buffer_muzero.py
  lzero/model/common.py
  lzero/model/unizero_model.py
  lzero/model/unizero_world_models/world_model.py
  lzero/policy/unizero.py
  lzero/worker/muzero_collector.py
  requirements.txt
  zoo/jericho/__init__.py
  zoo/jericho/configs/jericho_ppo_config.py
  zoo/jericho/configs/jericho_unizero_config.py
  zoo/jericho/configs/jericho_unizero_segment_config.py
  zoo/jericho/envs/__init__.py
  zoo/jericho/envs/jericho_env.py
  zoo/jericho/envs/test_jericho_env.py
Labels: environment, config

#333 feature(xjy): add save_replay and collect_episode_data option in jericho
  zoo/jericho/envs/jericho_env.py
Labels: enhancement

#335 fix(cmarlin): fix random_policy for len(ready_env_id) < collector_env_num
  lzero/policy/random_policy.py
Labels: bug

#266 feature(pu): add rope that use the true timestep index as pos_index
  lzero/entry/train_unizero.py
  lzero/entry/train_unizero_segment.py
  lzero/entry/utils.py
  lzero/mcts/buffer/game_buffer_sampled_unizero.py
  lzero/mcts/buffer/game_buffer_unizero.py
  lzero/mcts/buffer/game_segment.py
  lzero/mcts/tree_search/mcts_ctree.py
  lzero/mcts/tree_search/mcts_ctree_sampled.py
  lzero/model/sampled_unizero_model.py
  lzero/model/unizero_model.py
  lzero/model/unizero_world_models/README.md
  lzero/model/unizero_world_models/README_zh.md
  lzero/model/unizero_world_models/transformer.py
  lzero/model/unizero_world_models/world_model.py
  lzero/policy/sampled_unizero.py
  lzero/policy/unizero.py
  lzero/worker/muzero_collector.py
  lzero/worker/muzero_evaluator.py
  lzero/worker/muzero_segment_collector.py
  requirements.txt
  zoo/atari/config/atari_unizero_config.py
  zoo/atari/config/atari_unizero_segment_config.py
  zoo/atari/envs/atari_lightzero_env.py
  zoo/classic_control/cartpole/config/cartpole_unizero_config.py
  zoo/classic_control/cartpole/envs/cartpole_lightzero_env.py
  zoo/dmc2gym/config/dmc2gym_state_suz_segment_config.py
  zoo/dmc2gym/envs/dmc2gym_lightzero_env.py
Labels: enhancement, algorithm
